title: Diagrams
description: This is a diagram API.

image: https://postman-toolboxes2.s3.amazonaws.com/assets/api.png

#url: /diagrams
url: /

email: kin@postman.com

github_user: postman-open-technologies
github_repo: diagrams
github_branch: main

version:      1.1.1
markdown:     kramdown

diagrams_base_url: https://pt5fqvxp05.execute-api.us-west-1.amazonaws.com/staging